### ISSUE TITLE
Installing the CASPR

### ISSUE THREAD

**Issue by mabiaoxiaopang** [darwinlau/CASPR#2] opened 2016-12-21 02:55 UTC
Hello Prof.Lau ,
 I am a student and studying the CASPR . When installing the CASPR, I have a few problems. The WorkSpace Simulator does not work.  I also don't know what to do when reading the sentence'To allow for CASPR to access the compiled qhull code, move the compiled version of the code to the subdirectory *dependencies* ' 
Thank you for your consideration.

**Comment by mabiaoxiaopang** [comment] 2016-12-21 03:10
@darwinlau

**Comment by darwinlau** [comment] 2016-12-21 15:25
Hi! Thanks for raising an issue on this. We will look into the Workspace Simulator ASAP and reply. Also, we will update the instructions of the installation to be more clear. But essentially what was meant was, if you want to use the features that require qhull, you would need to compile qhull and then move it into the folder ~/dependencies/qhull (assuming ~/ is where you put CASPR). 

@jonathaneden Do you have any more details to add here?

**Comment by mabiaoxiaopang** [comment] 2016-12-23 01:25
Dear professor.Lau,
Thank you very much for your explanation.It was great help.
Sincerely,
Ma Biao

At 2016-12-21 23:25:05, "Darwin Lau" <notifications@github.com> wrote:


Hi! Thanks for raising an issue on this. We will look into the Workspace Simulator ASAP and reply. Also, we will update the instructions of the installation to be more clear. But essentially what was meant was, if you want to use the features that require qhull, you would need to compile qhull and then move it into the folder ~/dependencies/qhull (assuming ~/ is where you put CASPR).

@jonathaneden Do you have any more details to add here?

**Comment by jonathaneden** [comment] 2017-01-04 07:28
Hi,
Thanks again for raising this issue.  We have looked into the workspace simulator and found that the GUI for the simulator wasn't displaying properly. This would have made it not possible to set the grid parameters.  Was this the issue that you observed? Otherwise the simulator appears to be working on the tests that we have run in the new updated version.  Please try with the new updated version, if there are still issues please let us know of any further details regarding the failure and we will fix it ASAP.
Thanks and Regards,
Jonathan

**Comment by darwinlau** [comment] 2017-02-06 01:23
Hi @mabiaoxiaopang,

Just wondering whether the issue is OK now and whether there's anything thing outstanding you need help with? If not, I will close the issue.

**Comment by 1010195126** [comment] 2017-06-29 02:59
Hello Prof.Lau ,
      I downloaded the CASPR,but it doesn't work.So I want to detail install specification or complete CASPR document.I hope you can give me a help  at your convenience.My E-mail:1010195126@qq.com.
Thanks and Regards

**Comment by 1010195126** [comment] 2017-06-29 03:03
@darwinlau

**Comment by darwinlau** [comment] 2017-06-29 07:17
Hi @1010195126, thank you for your message. Step-by-step instructions to install and to start to use CASPR can be found at our youtube videos https://www.youtube.com/playlist?list=PLZCfv3Lre4aVbsS8zFYlg2x-kPuB-rrRC. Also, if you could e-mail me (darwinlau@mae.cuhk.edu.hk) more details about the error messages and also screenshots then I can help you resolve it. Also please let me know the version of matlab you are using. 

Thanks

**Closed** 2017-06-29 20:38 UTC
